version: '3'

services:
  web_server:
    build:
      context: .
      dockerfile: ./docker/web_server/Dockerfile
    container_name: 'web_server'
    privileged: true
    environment:
      TZ: '${TZ}'
      MYSQL_SERVER_NAME: 'db_server'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - "./www/html/:/var/www/html/"
    ports:
      - 8080:80
      - 8443:443

  db_server:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: 'db_server'
    privileged: true
    restart: always
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./db_data/:/var/lib/mysql/
      - ./docker/db_server/init_db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./docker/db_server/insert_data.sql:/docker-entrypoint-initdb.d/2.sql
      
  phpmyadmin:
    image: phpmyadmin
    container_name: 'phpmyadmin'
    restart: always
    environment:
      PMA_HOST: 'db_server'
      PMA_USER: 'root'
      PMA_PASSWORD: '${MYSQL_ROOT_PASS}'
    ports:
      - "8081:80"


