name: Deploy

on:
  workflow_dispatch:
  push:
    branches: main
    
jobs:
  deploy:
    name: Deploy source to eva, update database if modified
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/eva.key
          chmod 600 ~/.ssh/eva.key
          cat >>~/.ssh/config <<END
          Host eva
            HostName eva.fit.vutbr.cz
            User $SSH_USER
            IdentityFile ~/.ssh/eva.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Check out
        uses: actions/checkout@v3
        
      - name: Deploy source
        run: |
          cat >${{ github.workspace }}/www/html/includes/secrets.php <<END
          <?php
            \$servername = 'localhost';
            \$username = '$SSH_USER';
            \$password = '$MYSQL_PASSWORD';
            \$dbname = '$SSH_USER';
          ?>
          END
          
          scp -r ${{ github.workspace }}/www/html/* eva:~/WWW/IIS
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        
      -name: Reset database
        run: |
          scp ${{ github.workspace }}/docker/db_server/* eva:~
          ssh eva "bash -s" -- < ${{ github.workspace }}/reset_database.sh ${{ secrets.SSH_USER }} ${{ secrets.MYSQL_PASSWORD }}
